/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufro.proyectoges.vista;

import ufro.proyectoges.backend.entidades.Administrador;
import ufro.proyectoges.backend.entidades.Monitor;
import ufro.proyectoges.backend.entidades.Persona;
import ufro.proyectoges.backend.entidades.Registrador;
import ufro.proyectoges.backend.herramientas.HerramientaMonitor;
import ufro.proyectoges.backend.herramientas.HerramientaRegistrador;

/**
 * Esta clase maneja la visualizacion de la Ventana de Menu Principal
 *
 * @author Roald
 */
public class Menu extends javax.swing.JFrame {

    private Persona persona;

    /**
     * Creates new form Menu Constructor de la ventana Menu
     *
     * @param persona Recibe un objeto clase Persona, que alude a la persona que
     * esta utilizando el sistema
     */
    public Menu(Persona persona) {
        initComponents();
        this.persona = persona;
        if (persona.getHerramientaPersona() == null) {
            switch (persona.getTipo_persona()) {
                case "REGISTRADOR":
                    this.persona = new Registrador(persona.getId(),persona.getNombre(), persona.getRut(), persona.getClave());
                    break;
                case "MONITOR":
                    this.IngresoPacientesJButton.setVisible(false);
                    this.persona = new Monitor(persona.getId(),persona.getNombre(), persona.getRut(), persona.getClave());
                    break;
                default:
                    System.out.println("caso default");
                    break;
            }
        }

        
        this.setTitle("TIPO DE CUENTA: " + persona.getTipo_persona());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloJLabel = new javax.swing.JLabel();
        MenuJLabel = new javax.swing.JLabel();
        IngresoPacientesJButton = new javax.swing.JButton();
        BusquedaPacientesJButton = new javax.swing.JButton();
        DescargaBaseDatosJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoGES - Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloJLabel.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        TituloJLabel.setText("GEST-ION");
        getContentPane().add(TituloJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 26, -1, -1));

        MenuJLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuJLabel.setText("MENU");
        getContentPane().add(MenuJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 104, -1, -1));

        IngresoPacientesJButton.setBackground(new java.awt.Color(102, 204, 255));
        IngresoPacientesJButton.setText("Ingreso de Casos de Pacientes");
        IngresoPacientesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoPacientesJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IngresoPacientesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 220, 51));

        BusquedaPacientesJButton.setBackground(new java.awt.Color(102, 204, 255));
        BusquedaPacientesJButton.setText("Busqueda de Casos de Pacientes");
        BusquedaPacientesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaPacientesJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BusquedaPacientesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, 46));

        DescargaBaseDatosJButton.setBackground(new java.awt.Color(102, 204, 255));
        DescargaBaseDatosJButton.setText("Descarga de Base de Datos");
        DescargaBaseDatosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargaBaseDatosJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DescargaBaseDatosJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 43));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/med1a.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este metodo maneja la apertura y muestra de datos para la ventana Ingreso
     * de Pacientes
     *
     * @param evt Este evento se genenera cuando se hace click en el boton
     * Ingreso de Casos de Pacientes
     */
    private void IngresoPacientesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoPacientesJButtonActionPerformed
        // TODO add your handling code here:
        new IngresoCasoPaciente((Registrador) persona).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IngresoPacientesJButtonActionPerformed
    /**
     * Este metodo gestiona la visualizacion y muestra de datos de la ventana
     * Busqueda de Pacientes
     *
     * @param evt Este evento se genera al hacer click en el boton Busqueda de
     * Casos de Pacientes
     */
    private void BusquedaPacientesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaPacientesJButtonActionPerformed
        new BusquedaPaciente(persona,this).setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaPacientesJButtonActionPerformed
    /**
     * Este metodo gestiona la apertura y muestra de datos de la ventana
     * Descarga de Base de Datos de Casos de Pacientes
     *
     * @param evt Este evento se genera al hacer click en el boton Descarga de
     * Base de Datos
     */
    private void DescargaBaseDatosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargaBaseDatosJButtonActionPerformed
        // TODO add your handling code here:
        new DescargabaseDatos(persona).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DescargaBaseDatosJButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedaPacientesJButton;
    private javax.swing.JButton DescargaBaseDatosJButton;
    private javax.swing.JButton IngresoPacientesJButton;
    private javax.swing.JLabel MenuJLabel;
    private javax.swing.JLabel TituloJLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
